"""
Database models for chess lessons.
"""

from sqlalchemy import Column, Integer, String, Text, DateTime, ForeignKey, JSON, Boolean
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from app.core.database import Base


class Lesson(Base):
    """
    Chess lesson generated by the AI agent.
    Contains multiple lesson comments with annotations and questions.
    """
    __tablename__ = "lessons"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    game_id = Column(Integer, ForeignKey("games.id"), nullable=True)
    
    title = Column(String(255), nullable=False)
    description = Column(Text, nullable=True)
    
    # Lesson metadata
    focus_areas = Column(JSON, nullable=True)  # List of focus areas
    user_elo_at_creation = Column(Integer, nullable=False)
    
    # Lesson status
    status = Column(String(50), default="generating")  # generating, completed, failed
    error_message = Column(Text, nullable=True)
    
    # Timestamps
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    completed_at = Column(DateTime(timezone=True), nullable=True)
    
    # Relationships
    user = relationship("User", back_populates="lessons")
    game = relationship("Game", back_populates="lessons")
    comments = relationship("LessonComment", back_populates="lesson", cascade="all, delete-orphan")


class LessonComment(Base):
    """
    Individual comment/step within a lesson.
    Contains position, text, annotations, and optional question.
    """
    __tablename__ = "lesson_comments"

    id = Column(Integer, primary_key=True, index=True)
    lesson_id = Column(Integer, ForeignKey("lessons.id"), nullable=False)
    
    # Comment order
    step_number = Column(Integer, nullable=False)
    
    # Position info
    position_fen = Column(String(255), nullable=False)
    move_to_make = Column(String(10), nullable=True)  # UCI move to demonstrate
    
    # Content
    text = Column(Text, nullable=False)  # Markdown formatted commentary
    
    # Visual annotations (stored as JSON)
    annotations = Column(JSON, default=[])
    
    # Interactive question (stored as JSON)
    question = Column(JSON, nullable=True)
    
    # Timestamps
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    
    # Relationships
    lesson = relationship("Lesson", back_populates="comments")


class UserLessonProgress(Base):
    """
    Track user progress through lessons.
    Records which steps completed, answers given, etc.
    """
    __tablename__ = "user_lesson_progress"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    lesson_id = Column(Integer, ForeignKey("lessons.id"), nullable=False)
    
    # Progress tracking
    current_step = Column(Integer, default=0)
    completed = Column(Boolean, default=False)
    
    # User answers to questions (JSON: {step_number: answer})
    answers = Column(JSON, default={})
    
    # Timestamps
    started_at = Column(DateTime(timezone=True), server_default=func.now())
    completed_at = Column(DateTime(timezone=True), nullable=True)
    last_accessed = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())
    
    # Relationships
    user = relationship("User")
    lesson = relationship("Lesson")
